"""
statement.py - generates the weekly Trailblaze statement as an HTML file.
Usage:  python3 statement.py          (covers the last 7 days)
Output: statement.html  (open in any browser; email delivery comes later)
"""
import time
from datetime import datetime, timezone
from pathlib import Path
import db

DAYS = 7
now = int(time.time())
since = now - DAYS * 86400

con = db.connect()
labels = {r["address"]: r["name"] for r in con.execute("SELECT address, name FROM labels")}
def name(a): return labels.get(a, a[:8] + "…" + a[-4:])

def fmt_ts(ts): return datetime.fromtimestamp(ts, tz=timezone.utc).strftime("%b %d")

rows_html = []
grand_out = grand_in = 0.0

for w in con.execute("SELECT address, nickname FROM wallets"):
    wallet, nick = w["address"], (w["nickname"] or w["address"][:12])

    tot = con.execute("""
        SELECT SUM(CASE WHEN from_addr=:w THEN amount ELSE 0 END) AS out_usd,
               SUM(CASE WHEN from_addr!=:w THEN amount ELSE 0 END) AS in_usd,
               COUNT(*) AS n
        FROM transfers WHERE wallet=:w AND ts >= :s
    """, {"w": wallet, "s": since}).fetchone()
    out_usd, in_usd = tot["out_usd"] or 0, tot["in_usd"] or 0
    grand_out += out_usd; grand_in += in_usd

    raw = con.execute("""
        SELECT CASE WHEN from_addr=:w THEN to_addr ELSE from_addr END AS other,
               COUNT(*) n,
               SUM(CASE WHEN from_addr=:w THEN amount ELSE 0 END) AS out_usd,
               SUM(CASE WHEN from_addr!=:w THEN amount ELSE 0 END) AS in_usd
        FROM transfers WHERE wallet=:w AND ts >= :s
        GROUP BY other
    """, {"w": wallet, "s": since}).fetchall()
    # merge by LABEL, not address (two addresses can share one name)
    merged = {}
    for r in raw:
        m = merged.setdefault(name(r["other"]), {"n": 0, "out_usd": 0.0, "in_usd": 0.0})
        m["n"] += r["n"]; m["out_usd"] += r["out_usd"]; m["in_usd"] += r["in_usd"]
    top = [{"other": k, "n": v["n"], "out_usd": v["out_usd"], "in_usd": v["in_usd"]}
           for k, v in sorted(merged.items(),
                              key=lambda x: -(x[1]["out_usd"] + x[1]["in_usd"]))][:8]

    n_alerts = con.execute(
        "SELECT COUNT(*) c FROM alerts WHERE wallet=? AND first_ts >= ?",
        (wallet, since)).fetchone()["c"]

    lines = "".join(
        f"<tr><td>{r['other']}</td><td class='r'>{r['n']}</td>"
        f"<td class='r'>${r['in_usd']:.2f}</td><td class='r'>${r['out_usd']:.2f}</td></tr>"
        for r in top) or "<tr><td colspan=4>No activity this period.</td></tr>"

    alert_note = (f"<p class='alert'>&#9888; {n_alerts} alert(s) this period - see dashboard.</p>"
                  if n_alerts else "<p class='ok'>No anomalies detected this period.</p>")

    rows_html.append(f"""
    <div class="card">
      <h2>{nick}</h2>
      <p class="addr">{wallet}</p>
      <p><b>${out_usd:,.2f}</b> spent · <b>${in_usd:,.2f}</b> received ·
         {tot['n']} transfers in the last {DAYS} days</p>
      {alert_note}
      <table>
        <tr><th>counterparty</th><th class='r'>txs</th><th class='r'>in</th><th class='r'>out</th></tr>
        {lines}
      </table>
    </div>""")

html = f"""<!doctype html><html><head><meta charset="utf-8">
<title>Trailblaze Statement</title>
<style>
 body {{ font-family: Georgia, serif; color:#111; max-width:680px; margin:40px auto; padding:0 20px; }}
 h1 {{ font-size:28px; margin-bottom:0; }}
 .sub {{ color:#666; margin-top:4px; }}
 .card {{ border-top:2px solid #111; margin-top:32px; padding-top:8px; }}
 .addr {{ color:#999; font-family:monospace; font-size:11px; }}
 table {{ width:100%; border-collapse:collapse; font-size:14px; margin-top:8px; }}
 th {{ text-align:left; color:#666; font-weight:normal; border-bottom:1px solid #ddd; padding:4px 0; }}
 td {{ padding:5px 0; border-bottom:1px solid #f0f0f0; }}
 .r {{ text-align:right; }}
 .alert {{ color:#b00; font-weight:bold; }}
 .ok {{ color:#2a7; }}
 .foot {{ color:#999; font-size:11px; margin-top:40px; }}
</style></head><body>
<h1>Trailblaze</h1>
<p class="sub">Weekly statement · {fmt_ts(since)} - {fmt_ts(now)} ·
 total spent ${grand_out:,.2f} · total received ${grand_in:,.2f}</p>
{''.join(rows_html)}
<p class="foot">Generated by Trailblaze - the expense ledger of the agent economy.
Read-only: we hold no keys and move no money.</p>
</body></html>"""

out = Path(__file__).parent / "statement.html"
out.write_text(html)
con.close()
print(f"Statement written: {out.name}  (open it: open statement.html)")
